### ISSUE TITLE
Documentation Drive Week 3

### ISSUE THREAD

**Issue by buoyantair** [ssbc/ssb-blobs#14]
#### Rate the current state of the documentation out of 10.
3

#### Is it clear what this is used for?
Yes but there needs to be a lot of clarity in specific areas like the protocol.

##### Protocol

- While explaining how the peers initially connect to find a specific blob, the `blob_size` property is not explained properly.
- There is also no clear explanation of how a particular peer found a `blob_id` before it starts requesting other peers.
- How do this particular mechanism of asking peers for other blobs enable a peer to publish a "secret" blob without creating a permanent cryptographic record of that blob?
- When a blob is uploaded by a peer, that specific peer as for the docs starts to pretend that it wants the same blob. Since other nodes in contact with this publishing node employ sympathetic wants, how will the blob eventually end up with the neighbouring blobs when the publishing blob is just pretending? Will there be a time when after a couple of "sympathetic wants" from neighbouring peers, the publishing peer turns around and discloses the blob for peers to replicate?

#### is there api documentation?
Yes & No. 

While documentation for blobs config is present, API docs for all the properties / methods found in `index.js` is not present.

**Undocumented api list**
- exports.manifest
- exports.name
- exports.version
- exports.permissions
- exports.permissions.anonymous
- exports.permissions.allow
- exports.init

#### read code, do you see any undocumented methods?
Yes

#### for a method is there any undocumented options?
Yes

**Comment by dominictarr** [comment]
thanks! great detail!

All those missing api documentation are standard for a secret-stack plugin.
that should be explained here: https://github.com/ssbc/secret-stack/issues/37
