### ISSUE TITLE
How can I prevent my device from downloading unknown blobs?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-blobs#23]
I'd like to avoid downloading any blobs unless a friend has posted about it to their append-only log. I'm concerned that right now I'm downloading data from unknown network peers with no accountability.

The documentation says that I can set `sympathy` to `0` to prevent my device from *requesting* blobs I don't want, but does this also stop other devices from pushing blobs onto my device?

**Comment by dominictarr** [comment]
yes. blobs.push and blobs.add are only exposed to a client with full access (I.e. the same private key) remote peers can only tell you they have a blob, and then you ask for it. in ssb everything is pull, for reasons like this.

**Comment by christianbundy** [comment]
Cool, thanks. Am I correct in my understanding that `sympathy > 0` lets network peers basically push to your device? I think someone [within 3 network hops] has been *want*ing a handful of blobs and then later is uploading them to the network, which adds them to all of the devices within sympathy range.

**Comment by dominictarr** [comment]
sympathy is how many hops out (in terms of peer connections) you'll automatically pull from, yes that's in practice the same as a push.
