### ISSUE TITLE
why does blobs.add return `undefined` for the hash?

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-blobs#25]
Trying to add an 'avatar' type image in sbot.
https://github.com/nichoth/eventual/blob/master/src/subscribe.js#L41

![image](https://user-images.githubusercontent.com/5776508/73587464-1276f300-4471-11ea-957e-90bc78d8bed7.png)

**Comment by christianbundy** [comment]
Sorry, I don't think I understand. What's the problem you're facing, or maybe what do you expect to happen instead?

**Comment by nichoth** [comment]
yes, so there should be two possible outputs, either err is equal to something, or `err` is null and hash is valid. this is something else -- no error but `hash` is not a valid hash. I ended up getting around this by taking the hash in the client as a separate function call. I think this is about making the behavior the same as the documentation.

**Comment by christianbundy** [comment]
Hmm, that's very strange. I just tested locally and it looks like it's giving me what I expect, but I'm using `blobs.add(hash, cb)`. :thinking:

**Comment by nichoth** [comment]
ok, so it looks like you are also getting the hash as a separate step, and the `blobs.add` call returns what was passed in. Looking at the docs https://scuttlebot.io/apis/scuttlebot/blobs.html this is what it says should happen. I'm not sure why I was confused when I opened this, thanks for looking.
