### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by retog** [ssbc/ssb-blobs#32]
I've been using https://scuttlebot.io/apis/scuttlebot/blobs.html as documentation but it seems to be outdated. I found that the `want` method now returns a promise and no longer seems to support the callback. Also, the `push` method is not documented.

**Comment by retog** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

I think it is.

**Comment by mixmix** [comment]
Thanks @retog. I'm looking at documenting the api here this week.

I'm not sure why it's want would return a promise, in the code it's callback based.
I have a feeling someone else in the stack might be providing promise sugar but I'm not sure. I don't plan to be investigating that at this stage.

**Comment by mixmix** [comment]
There's some docs of api in help.js
https://www.github.com/ssbc/ssb-blobs/tree/master/help.js

Will be checking that's up to date too

**Comment by retog** [comment]
> 
> 
> Thanks @retog. I'm looking at documenting the api here this week.
> 
> I'm not sure why it's want would return a promise, in the code it's callback based.
> I have a feeling someone else in the stack might be providing promise sugar but I'm not sure. I don't plan to be investigating that at this stage.

Yes, this appears to be added by muxrpc. Not sure why I was under the impression that the callback would no longer work.

**Comment by mixmix** [comment]
I've added some docs now. Going to close this for the moment
